name: Data Transfer Unit Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Install package
        working-directory: data-transfer/pontoon
        run: pip install .

      - name: Run unit tests
        working-directory: data-transfer/pontoon
        run: pytest -s tests/unit/